import type {
  Exercise,
  MealType,
  WeekdayKey,
  WorkoutDay,
  WorkoutExercise,
  WorkoutPhase,
} from "@/lib/health/types";

export const athleteProfile = {
  height: "5'10\" (178 cm)",
  startingWeightKg: 62,
  goalWeightKg: "67-70",
  programDurationWeeks: 12,
  trainingDaysPerWeek: 6,
  restDay: "Sunday",
  diet: "Vegan (no milk/dairy)",
  dailyProteinTarget: "120-130g",
  dailyCalorieTarget: "2600-2800 kcal",
};

export const quickFoodPresets: Array<{ label: string; protein: number; calories: number }> = [
  { label: "Protein Shake", protein: 30, calories: 250 },
  { label: "Dal + Rice", protein: 20, calories: 450 },
  { label: "Soy Chunks (50g)", protein: 26, calories: 170 },
  { label: "Tofu (200g)", protein: 20, calories: 180 },
  { label: "PB + Banana Shake", protein: 15, calories: 350 },
  { label: "Roti + Rajma", protein: 18, calories: 400 },
  { label: "Oats + PB", protein: 14, calories: 400 },
  { label: "Handful of peanuts", protein: 7, calories: 170 },
];

export const mealOptions: MealType[] = [
  "Breakfast",
  "Snack",
  "Lunch",
  "Pre-Workout",
  "Post-Workout Shake",
  "Dinner",
  "Before Bed",
];

export const pullUpMilestones = [
  "Dead hang 30s",
  "Negative pull-up 5s",
  "First full pull-up",
  "3 consecutive pull-ups",
  "5 consecutive pull-ups",
  "8 consecutive pull-ups",
];

const ex = (exercise: Exercise) => exercise;

export const exercises: Exercise[] = [
  ex({
    id: "push-ups",
    name: "Push-ups",
    type: "bodyweight",
    muscleGroup: "chest",
    equipment: "None",
    notes: "Full range, chest to floor",
    isTimeBased: false,
    formTip: "Brace core and keep body as one line.",
  }),
  ex({
    id: "bench-press",
    name: "Bench Press",
    type: "weighted",
    muscleGroup: "chest",
    equipment: "Barbell + bench",
    notes: "Controlled tempo, full range",
    isTimeBased: false,
    formTip: "Drive feet into floor and retract shoulder blades.",
  }),
  ex({
    id: "chest-press-machine",
    name: "Chest Press Machine",
    type: "machine",
    muscleGroup: "chest",
    equipment: "Chest press machine",
    notes: "2s up, 2s down tempo",
    isTimeBased: false,
    formTip: "Keep wrists stacked and avoid shoulder shrugging.",
  }),
  ex({
    id: "chest-fly-machine",
    name: "Chest Fly Machine",
    type: "machine",
    muscleGroup: "chest",
    equipment: "Fly machine",
    notes: "Squeeze hard at peak contraction",
    isTimeBased: false,
    formTip: "Slight elbow bend and controlled return.",
  }),
  ex({
    id: "diamond-push-ups",
    name: "Diamond Push-ups",
    type: "bodyweight",
    muscleGroup: "triceps",
    equipment: "None",
    notes: "Hands together, elbows tight to body",
    isTimeBased: false,
    formTip: "Keep elbows tucked and move slow.",
  }),
  ex({
    id: "tricep-bench-dips",
    name: "Tricep Bench Dips",
    type: "bodyweight",
    muscleGroup: "triceps",
    equipment: "Bench",
    notes: "Feet on floor, deep stretch",
    isTimeBased: false,
    formTip: "Drop shoulders down and avoid flaring elbows.",
  }),
  ex({
    id: "pike-push-ups",
    name: "Pike Push-ups",
    type: "bodyweight",
    muscleGroup: "shoulders",
    equipment: "None/bench",
    notes: "Hips high, head towards floor",
    isTimeBased: false,
    formTip: "Think vertical press with hips over shoulders.",
  }),
  ex({
    id: "incline-push-ups",
    name: "Incline Push-ups",
    type: "bodyweight",
    muscleGroup: "chest",
    equipment: "Bench",
    notes: "Hands on bench, progress to flat",
    isTimeBased: false,
    formTip: "Touch chest lightly to incline each rep.",
  }),
  ex({
    id: "close-grip-push-ups",
    name: "Close-Grip Push-ups",
    type: "bodyweight",
    muscleGroup: "triceps",
    equipment: "None",
    notes: "Hands shoulder width, elbows tight",
    isTimeBased: false,
    formTip: "Keep triceps loaded by tucked elbows.",
  }),
  ex({
    id: "db-lateral-raises",
    name: "Dumbbell Lateral Raises",
    type: "weighted",
    muscleGroup: "shoulders",
    equipment: "Dumbbells",
    notes: "Light weight, control the movement",
    isTimeBased: false,
    formTip: "Lead with elbows and stop around shoulder height.",
  }),
  ex({
    id: "front-lateral-combo",
    name: "Front Raise + Lateral Raise Combo",
    type: "weighted",
    muscleGroup: "shoulders",
    equipment: "Dumbbells",
    notes: "Alternate front and side",
    isTimeBased: false,
    formTip: "Use lighter load and keep tempo smooth.",
  }),
  ex({
    id: "pseudo-planche-lean",
    name: "Pseudo Planche Lean",
    type: "timed",
    muscleGroup: "shoulders",
    equipment: "None",
    notes: "Hands by hips, lean forward",
    isTimeBased: true,
    formTip: "Protract shoulders and maintain rigid core.",
  }),
  ex({
    id: "archer-push-ups",
    name: "Archer Push-ups",
    type: "bodyweight",
    muscleGroup: "chest",
    equipment: "None",
    notes: "Phase 3: one arm does most work",
    isTimeBased: false,
    formTip: "Shift weight over working arm each rep.",
  }),
  ex({
    id: "typewriter-push-ups",
    name: "Typewriter Push-ups",
    type: "bodyweight",
    muscleGroup: "chest",
    equipment: "None",
    notes: "Phase 3: move side to side at top",
    isTimeBased: false,
    formTip: "Keep chest low while shifting laterally.",
  }),
  ex({
    id: "push-up-burnout",
    name: "Push-up Burnout",
    type: "bodyweight",
    muscleGroup: "chest",
    equipment: "None",
    notes: "1 set to absolute failure",
    isTimeBased: false,
    formTip: "No ego: stop only when form collapses.",
  }),
  ex({
    id: "dead-hang",
    name: "Dead Hang",
    type: "timed",
    muscleGroup: "back",
    equipment: "Pull-up bar",
    notes: "Crush the bar, build grip",
    isTimeBased: true,
    formTip: "Keep active shoulders and full grip tension.",
  }),
  ex({
    id: "negative-pull-ups",
    name: "Negative Pull-ups",
    type: "bodyweight",
    muscleGroup: "back",
    equipment: "Pull-up bar",
    notes: "Jump up, lower 5-7 seconds",
    isTimeBased: false,
    formTip: "Control every inch of the eccentric.",
  }),
  ex({
    id: "pull-ups",
    name: "Pull-ups",
    type: "bodyweight",
    muscleGroup: "back",
    equipment: "Pull-up bar",
    notes: "Full dead hang to chin over bar",
    isTimeBased: false,
    formTip: "Start from dead hang and lead chest to bar.",
  }),
  ex({
    id: "chin-up-negatives",
    name: "Chin-up Negatives",
    type: "bodyweight",
    muscleGroup: "biceps",
    equipment: "Pull-up bar",
    notes: "Underhand grip, bicep focused",
    isTimeBased: false,
    formTip: "Squeeze biceps while descending slowly.",
  }),
  ex({
    id: "lat-pulldown-wide",
    name: "Lat Pulldown Wide Grip",
    type: "machine",
    muscleGroup: "back",
    equipment: "Lat pulldown",
    notes: "Lean back slightly, squeeze",
    isTimeBased: false,
    formTip: "Pull elbows to pockets.",
  }),
  ex({
    id: "lat-pulldown-close",
    name: "Lat Pulldown Close/Underhand Grip",
    type: "machine",
    muscleGroup: "back",
    equipment: "Lat pulldown",
    notes: "Squeeze shoulder blades",
    isTimeBased: false,
    formTip: "Pause at chest and control release.",
  }),
  ex({
    id: "inverted-rows",
    name: "Inverted Rows",
    type: "bodyweight",
    muscleGroup: "back",
    equipment: "Barbell/Smith machine",
    notes: "Body straight, pull chest to bar",
    isTimeBased: false,
    formTip: "Keep hips high and avoid neck jutting.",
  }),
  ex({
    id: "db-rows",
    name: "Dumbbell Rows",
    type: "weighted",
    muscleGroup: "back",
    equipment: "Dumbbells + bench",
    notes: "Knee on bench, pull to hip",
    isTimeBased: false,
    formTip: "Pause at top and avoid torso twist.",
  }),
  ex({
    id: "face-pulls",
    name: "Face Pulls",
    type: "weighted",
    muscleGroup: "shoulders",
    equipment: "Cable/band",
    notes: "Rear delts and posture",
    isTimeBased: false,
    formTip: "Pull toward nose/forehead with external rotation.",
  }),
  ex({
    id: "db-curls",
    name: "Dumbbell Bicep Curls",
    type: "weighted",
    muscleGroup: "biceps",
    equipment: "Dumbbells",
    notes: "Strict form, no swinging",
    isTimeBased: false,
    formTip: "Lock elbows and control lowering.",
  }),
  ex({
    id: "hammer-curls",
    name: "Hammer Curls",
    type: "weighted",
    muscleGroup: "biceps",
    equipment: "Dumbbells",
    notes: "Palms facing each other",
    isTimeBased: false,
    formTip: "Keep wrists neutral throughout.",
  }),
  ex({
    id: "incline-db-curls",
    name: "Incline Dumbbell Curls",
    type: "weighted",
    muscleGroup: "biceps",
    equipment: "Dumbbells + bench",
    notes: "Full stretch at bottom",
    isTimeBased: false,
    formTip: "Let arms hang and avoid shoulder roll.",
  }),
  ex({
    id: "concentration-curls",
    name: "Concentration Curls",
    type: "weighted",
    muscleGroup: "biceps",
    equipment: "Dumbbells",
    notes: "Elbow against inner thigh",
    isTimeBased: false,
    formTip: "Squeeze hard at top for one count.",
  }),
  ex({
    id: "curl-21s",
    name: "Curl 21s",
    type: "weighted",
    muscleGroup: "biceps",
    equipment: "Dumbbells/barbell",
    notes: "7 bottom + 7 top + 7 full = 1 set",
    isTimeBased: false,
    formTip: "Use smooth rhythm, no momentum.",
  }),
  ex({
    id: "oh-tricep-extension",
    name: "Overhead Tricep Extension",
    type: "weighted",
    muscleGroup: "triceps",
    equipment: "Dumbbell",
    notes: "One dumbbell, both hands",
    isTimeBased: false,
    formTip: "Keep elbows close and fixed.",
  }),
  ex({
    id: "muscle-up-negatives",
    name: "Muscle-up Negatives",
    type: "bodyweight",
    muscleGroup: "back",
    equipment: "Pull-up bar",
    notes: "Phase 3: jump above, lower through",
    isTimeBased: false,
    formTip: "Control transition from dip to hang.",
  }),
  ex({
    id: "hanging-knee-raises",
    name: "Hanging Knee Raises",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "Pull-up bar",
    notes: "Controlled, knees to chest",
    isTimeBased: false,
    formTip: "Posterior tilt pelvis at top.",
  }),
  ex({
    id: "hanging-leg-raises",
    name: "Hanging Leg Raises",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "Pull-up bar",
    notes: "Straight legs, Phase 3 progression",
    isTimeBased: false,
    formTip: "Lift from core, avoid kipping.",
  }),
  ex({
    id: "lying-leg-raises",
    name: "Leg Raises Lying",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Lower back pressed into floor",
    isTimeBased: false,
    formTip: "Keep lumbar spine pinned throughout.",
  }),
  ex({
    id: "mountain-climbers",
    name: "Mountain Climbers",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Controlled pace, not speed",
    isTimeBased: false,
    formTip: "Drive knees with stable shoulders.",
  }),
  ex({
    id: "russian-twists",
    name: "Russian Twists",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Lean back, feet hovering",
    isTimeBased: false,
    formTip: "Rotate torso, not just hands.",
  }),
  ex({
    id: "plank-hold",
    name: "Plank Hold",
    type: "timed",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Squeeze glutes and quads",
    isTimeBased: true,
    formTip: "Neutral pelvis and packed shoulders.",
  }),
  ex({
    id: "plank-shoulder-taps",
    name: "Plank Shoulder Taps",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Minimise hip rotation",
    isTimeBased: false,
    formTip: "Widen feet for more anti-rotation control.",
  }),
  ex({
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    type: "timed",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Arms overhead, lower back down",
    isTimeBased: true,
    formTip: "Press low back flat and breathe shallow.",
  }),
  ex({
    id: "dead-bugs",
    name: "Dead Bugs",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Slow, opposite arm and leg",
    isTimeBased: false,
    formTip: "Move slowly and keep ribcage down.",
  }),
  ex({
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Slow, full rotation",
    isTimeBased: false,
    formTip: "Elbow to opposite knee with full twist.",
  }),
  ex({
    id: "v-ups",
    name: "V-ups",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Touch toes at top",
    isTimeBased: false,
    formTip: "Explode up and control the descent.",
  }),
  ex({
    id: "side-plank",
    name: "Side Plank",
    type: "timed",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Stack feet, hips high",
    isTimeBased: true,
    formTip: "Keep straight line from head to feet.",
  }),
  ex({
    id: "plank-to-push-up",
    name: "Plank to Push-up",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "None",
    notes: "Forearm to pushup, alternate lead",
    isTimeBased: false,
    formTip: "Minimize sway during transitions.",
  }),
  ex({
    id: "dragon-flag-negatives",
    name: "Dragon Flag Negatives",
    type: "bodyweight",
    muscleGroup: "abs",
    equipment: "Bench",
    notes: "Phase 3: slow lowering",
    isTimeBased: false,
    formTip: "Lower in one rigid segment.",
  }),
  ex({
    id: "crow-pose",
    name: "Crow Pose",
    type: "timed",
    muscleGroup: "full_body",
    equipment: "None",
    notes: "Use pillow in front!",
    isTimeBased: true,
    formTip: "Lean forward until feet float lightly.",
  }),
  ex({
    id: "lsit-tuck-hold",
    name: "L-Sit Tuck Hold",
    type: "timed",
    muscleGroup: "abs",
    equipment: "Floor/bars",
    notes: "Tucked knees, push through shoulders",
    isTimeBased: true,
    formTip: "Lock elbows and depress shoulders.",
  }),
  ex({
    id: "wall-handstand-hold",
    name: "Wall Handstand Hold",
    type: "timed",
    muscleGroup: "shoulders",
    equipment: "Wall",
    notes: "Phase 3: face wall, tight core",
    isTimeBased: true,
    formTip: "Ribs tucked and glutes squeezed.",
  }),
];

export const exerciseById = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise]));

const w = (
  exerciseId: string,
  sets: number,
  reps: string,
  restSeconds: number,
  extra?: Partial<WorkoutExercise>,
): WorkoutExercise => ({ exerciseId, sets, reps, restSeconds, ...extra });

const baseDays: WorkoutDay[] = [
  {
    dayOfWeek: "monday",
    name: "Push HEAVY - Chest & Triceps",
    focus: "Push",
    exercises: [
      w("bench-press", 4, "6-8", 120),
      w("chest-press-machine", 3, "8-12", 90),
      w("chest-fly-machine", 3, "10-12", 75),
      w("push-ups", 3, "max", 60, { supersetGroup: "A", supersetOrder: 1 }),
      w("diamond-push-ups", 3, "8-12", 60, { supersetGroup: "A", supersetOrder: 2 }),
      w("tricep-bench-dips", 3, "10-12", 60),
      w("db-lateral-raises", 3, "12-15", 45),
    ],
  },
  {
    dayOfWeek: "tuesday",
    name: "Pull HEAVY - Back & Biceps",
    focus: "Pull",
    exercises: [
      w("dead-hang", 3, "30s", 60),
      w("negative-pull-ups", 4, "3-5", 120),
      w("lat-pulldown-wide", 4, "8-10", 90),
      w("db-rows", 4, "8-10", 90),
      w("lat-pulldown-close", 3, "10-12", 75),
      w("db-curls", 3, "10-12", 60, { supersetGroup: "B", supersetOrder: 1 }),
      w("hammer-curls", 3, "10-12", 60, { supersetGroup: "B", supersetOrder: 2 }),
      w("face-pulls", 3, "12-15", 60),
    ],
  },
  {
    dayOfWeek: "wednesday",
    name: "Abs DESTROYER + Skills",
    focus: "Abs",
    exercises: [
      w("hanging-knee-raises", 4, "10-15", 60),
      w("lying-leg-raises", 3, "12-15", 45),
      w("plank-hold", 3, "45s", 45),
      w("hollow-body-hold", 3, "30s", 45),
      w("russian-twists", 3, "20", 45),
      w("mountain-climbers", 3, "30", 45),
      w("crow-pose", 3, "20s", 60, { supersetGroup: "C", supersetOrder: 1 }),
      w("lsit-tuck-hold", 3, "15s", 60, { supersetGroup: "C", supersetOrder: 2 }),
    ],
  },
  {
    dayOfWeek: "thursday",
    name: "Push HYPERTROPHY - Chest Shoulders Triceps",
    focus: "Push",
    exercises: [
      w("incline-push-ups", 4, "12-15", 60),
      w("chest-press-machine", 4, "10-12", 75),
      w("chest-fly-machine", 3, "12-15", 60),
      w("close-grip-push-ups", 3, "max", 60),
      w("pike-push-ups", 3, "8-10", 75),
      w("front-lateral-combo", 3, "12", 60),
      w("pseudo-planche-lean", 3, "20s", 60),
    ],
  },
  {
    dayOfWeek: "friday",
    name: "Pull HYPERTROPHY - Back & Biceps",
    focus: "Pull",
    exercises: [
      w("dead-hang", 3, "45s", 60),
      w("pull-ups", 4, "max", 120),
      w("inverted-rows", 3, "10-12", 75),
      w("lat-pulldown-close", 3, "12-15", 75),
      w("incline-db-curls", 3, "10-12", 60),
      w("concentration-curls", 3, "10-12", 60),
      w("curl-21s", 2, "21", 75),
      w("oh-tricep-extension", 2, "12-15", 60),
    ],
  },
  {
    dayOfWeek: "saturday",
    name: "Arms + Abs FINISHER",
    focus: "Abs",
    exercises: [
      w("db-curls", 4, "12", 45, { supersetGroup: "D", supersetOrder: 1 }),
      w("oh-tricep-extension", 4, "12", 45, { supersetGroup: "D", supersetOrder: 2 }),
      w("hanging-knee-raises", 3, "12-15", 45),
      w("plank-shoulder-taps", 3, "20", 45),
      w("bicycle-crunches", 3, "20", 45),
      w("v-ups", 3, "12", 45),
      w("side-plank", 2, "30s", 45),
      w("plank-to-push-up", 2, "12", 45),
    ],
  },
];

const phase2Days: WorkoutDay[] = baseDays.map((day) => ({
  ...day,
  exercises: day.exercises.map((exercise) => ({
    ...exercise,
    phaseNotes:
      day.focus === "Push"
        ? "Add 2.5kg weekly to bench and machine presses when reps hit top range."
        : day.focus === "Pull"
          ? "Add load or reps each week; prioritize strict pull-up quality first."
          : "Increase time-under-tension and reduce rest by 10s.",
    isDropSet: day.dayOfWeek === "thursday" && exercise.exerciseId === "chest-fly-machine",
  })),
}));

const phase3Days: WorkoutDay[] = phase2Days.map((day) => ({
  ...day,
  exercises: day.exercises
    .map((exercise) => {
      if (exercise.exerciseId === "push-ups") {
        return { ...exercise, exerciseId: "archer-push-ups", reps: "6-10" };
      }
      if (exercise.exerciseId === "incline-push-ups") {
        return { ...exercise, exerciseId: "typewriter-push-ups", reps: "6-10" };
      }
      if (exercise.exerciseId === "hanging-knee-raises") {
        return { ...exercise, exerciseId: "hanging-leg-raises", reps: "8-12" };
      }
      return {
        ...exercise,
        phaseNotes: "Phase 3 intensity: advanced variation + strict execution.",
      };
    })
    .concat(
      day.dayOfWeek === "monday"
        ? [w("push-up-burnout", 1, "failure", 0, { isBurnout: true, phaseNotes: "Final chest finisher." })]
        : day.dayOfWeek === "tuesday"
          ? [w("muscle-up-negatives", 3, "3", 120, { phaseNotes: "Skill strength progression." })]
          : day.dayOfWeek === "wednesday"
            ? [w("wall-handstand-hold", 3, "30s", 60)]
            : day.dayOfWeek === "saturday"
              ? [w("dragon-flag-negatives", 3, "5", 75, { phaseNotes: "Slow 5-7 second negative." })]
              : [],
    ),
}));

export const workoutPhases: WorkoutPhase[] = [
  {
    id: 1,
    label: "Phase 1",
    weeks: [1, 4],
    changesSummary: [
      "Master technique and full range of motion.",
      "Establish baseline numbers for each key lift and bodyweight movement.",
      "Focus on consistency and set completion quality.",
    ],
    days: baseDays,
  },
  {
    id: 2,
    label: "Phase 2",
    weeks: [5, 8],
    changesSummary: [
      "Add 2.5kg weekly to bench when top reps are achieved.",
      "Introduce strategic drop sets on hypertrophy accessories.",
      "Increase pull-up volume and tighten rest discipline.",
    ],
    days: phase2Days,
  },
  {
    id: 3,
    label: "Phase 3",
    weeks: [9, 12],
    changesSummary: [
      "Replace foundational push-up variations with archer/typewriter progressions.",
      "Upgrade abs and skill work to advanced holds/negatives.",
      "Push final-week intensity with burnout and milestone tests.",
    ],
    days: phase3Days,
  },
];

export const dayOrder: WeekdayKey[] = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];
